name: Automated deployment for ArgoCD

on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  deploy-argocd:
    name: Modifiy manifests to deploy with the newest version of images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify images version 
        run: |
          sed -i "s+matheoleger/frontend.*+matheoleger/frontend:$VERSION+g" frontend-deployment.yaml
          sed -i "s+matheoleger/order-service.*+matheoleger/order-service:$VERSION+g" order-service-deployment.yaml
          sed -i "s+matheoleger/user-service.*+matheoleger/user-service:$VERSION+g" user-service-deployment.yaml
          git config user.name matheoleger
          git config user.email matheo.leger@ynov.com
          git add .
          git commit -m "Updated images to $VERSION"
          git push origin main
        env:
          VERSION: ${{ github.event.client_payload.version }}